Invertus/dpdbaltics17

CHANGELOG.md, views/js/front/pudo.js
Map loading fix, when prestashop cache enabled
=> Dgs 74 /bugfix  Map loading fix, when prestashop cache enabled

CHANGELOG.md, config/config.yml, config/service.yml, controllers/admin/AdminDPDBalticsSettingsController.php, dpdbaltics.php, src/Config/Config.php, src/Exception/DpdCarrierException.php, src/Install/Installer.php, src/Logger/Logger.php, src/Repository/CarrierRepository.php, src/Repository/ProductRepository.php, src/Service/Carrier/CreateCarrierService.php, src/Service/Carrier/PrestashopCarrierRegenerationHandler.php, upgrade/Upgrade-3.2.6.php
Function deletes carriers and adds by DPD products
=> DGS 48 /carrier regeneration functionality without module reset

CHANGELOG.md, config/config.yml, config/service.yml, controllers/admin/AdminDPDBalticsAjaxShipmentsController.php, dpdbaltics.php, src/Factory/ShipmentDataFactory.php, src/Service/OrderService.php, src/Service/ShipmentService.php, src/Validate/Carrier/CarrierUpdateValidate.php, views/templates/hook/admin/partials/pudo-address.tpl
Problem was that carrier is not updated in default order table. Update logic added.
=> DGS-99 bugfix when order carrier cannot be changed in backoffice order view

CHANGELOG.md, views/js/front/pudo-search.js
- Bugfix, override in array method in javascript, as different jquery version act differently while executing function
=> DGS-98 bugfix when wrong jquery function is used, function override added

mails/lt/parcel-tracking.html
I changed the Lithuanian email template rendering out of stock template instead of tracking parcel template.
=> DGS-193 Change Lithuanian email template to right one

controllers/admin/AdminDPDBalticsAjaxShipmentsController.php
Missing template ID for shipment formatting
=> Missing template id for shipment

src/Install/Installer.php
While installing module name were missing it caused not loading tabs in the module.
=> Missing 3 param for tabs while install

composer.lock
I was thinking between remove all composer lock but decided to update it because old dpd-api was installed every time.
=> DGS-219/Composer-lock

views/js/front/pudo-search.js
There was a JS bug witch caused an error due to a mistake I have done extracting value from HTML element.
Previous error
=> Pudo search bug fix, causing error

dpdbaltics.php, sql/install/shipment.sql, upgrade/Upgrade-3.2.13.php
Seems like it is may be slow due to unindexed field. Can't 100% test it due to not having access to client database.
=> DGS-229 Slow order page list due to index

dpdbaltics.php
Missed version upgrade on previous PR. https://github.com/Invertus/dpdbaltics17/pull/80/files
=> DGS-229 Upgrading version

dpdbaltics.php
Small service call correction.
=> DGS-223/AdditionalShippingCosts-correction

dpdbaltics.php, src/Service/ShippingPriceCalculationService.php
Was showing incorrect prices after refreshing the page as it was returning current carrier price for each of DPD carriers.
=> DGS-229 current carrier instead of cart carrier

src/Util/StringUtility.php
https://github.com/DPDBaltics/PrestaShop-1.7/pull/50
=> Remove special characters

src/Entity/DPDPriceRule.php
Fixed service, exception was hidden due debug is turned off.
=> Service fix

src/Service/API/ShipmentApiService.php
Fix for issue if customer will make an order with an company name as empty space.
=> DGS-284/Added additional validation if company name is empty

views/templates/hook/admin/partials/pudo-info.tpl
Escaped variables from template file
=> Escaped variables from template file

src/Repository/PriceRuleRepository.php
On 8.0.3 version if guest does not have address it returns null and breaks the code
=> Price rule and country fix

dpdbaltics.php, src/Repository/ProductRepository.php
In DPD module settings products zones is Lithuania, but customer from Latvia (address country Latvia) can see the carrier as an option. 
Added additional validation to check the address country
=> DGS-310/ Carrier availability in country

dpdbaltics.php
Call to a member function getErrLog() on null
=> DGS-332/parcel error fix

views/js/front/pudo-search.js
Carrier parameter fix in ajax call to prevent from exception being thrown in back end
=> DGS-298/Carrier parameter fix
